version: '3.8'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
